### ISSUE TITLE
Unable to read scheme Monokai.icls

### ISSUE THREAD

**Issue by jairook** [benmarten/MonokaiAndroidStudio#2]
Cannot read scheme Monokai.icls  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142

This error came up while restarting the android studio..

**Comment by benmarten** [comment]
I've reexported the jar, can you please try again? Does it read the theme at all?

**Comment by jairook** [comment]
No luck,
Still showing the same error:
Cannot read scheme Monokai.icls  from '$ROOT_CONFIG$/colors': Unsupported color scheme version: 142

**Comment by benmarten** [comment]
Oh, wich Android Studio Version are u using?
I am using the 2.0 Preview, that might be the issue ...

**Comment by jairook** [comment]
Maybe, because my Studio version is stable 1.5.1

**Comment by benmarten** [comment]
Ok, I've fixed the jar. Please reimport, to delete your existing file:
`rm ~/Library/Preferences/AndroidStudio1.5/colors/Monokai.icls`

**Comment by jairook** [comment]
Thanks a lot,
It works great.
