### ISSUE TITLE
Change text background color when do rename operation

### ISSUE THREAD

**Issue by cikai** [benmarten/MonokaiAndroidStudio#3]
Hey, how could I change the text background color when do some operations like rename in studio ? 
Here I'm using android studio 3.0. Any help would be appreciate !

![avatar](http://cikai-netdisk.b0.upaiyun.com/studio-monokai-issue.png)

**Comment by benmarten** [comment]
![1](https://user-images.githubusercontent.com/5960238/38317695-80aaed92-37e2-11e8-9b7a-50f07e758a7a.jpg)
This should do it.

**Comment by cikai** [comment]
@benmarten  thanks a lot, it works : )
